version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: .
    volumes:
      - .:/app
    environment:
      - DEBUG=0
      - SECRET_KEY=your-secret-key
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - CORS_ALLOWED_ORIGINS=http://localhost:80,http://localhost:8000
      - CORS_ALLOW_ALL_ORIGINS=True
      - CORS_ALLOW_CREDENTIALS=True
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: 