version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/app
    environment:
      - DEBUG=0
      - SECRET_KEY=your-secret-key
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - REDIS_HOST=redis
      - REDIS_PORT=6380
    depends_on:
      - redis
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 